### ISSUE TITLE
Is this the Scary-Maze Flash Source?

### ISSUE THREAD

**Issue by lonnietc** [illyakurochkin/scary-maze-game#1]
Hello,

I am new to Flash and am looking for the source code to the "Scary-Maze" (swf) so that I can learn from it for a project that I would like to do.

https://www.playscarymazegame.net/play-scary-maze-game/

Is this it?
Thanks

**Comment by illyakurochkin** [comment]
Yes, I was trying to replicate this popular game. I'm not sure that this is the best code example to look into, because I was doing it when I just started my programming career.
